# Problem 4(a),(b)
require(readxl)
x <- read_excel("dobson6.3.xls", skip = 2)
par(mfrow=c(2,2))
plot(x$age, x$carbohydrate)
plot(x$weight, x$carbohydrate)
plot(x$protein, x$carbohydrate)
lmfit <- lm(carbohydrate ~ age + weight + protein, data=x)
summary(lmfit)
plot(fitted(lmfit), resid(lmfit))
abline(0,0)

# Problem 4(c)
lmfit2 <- lm(carbohydrate ~ age + protein, data=x)
summary(lmfit2)
